# Numpy (Numerical Python)

Pustaka Python open source yang digunakan di hampir semua bidang sains dan teknik. Pustaka Numpy beiris array multidimensional dan struktur data matriks. Numpy menambahkan struktur data yang kuat yang menjamin penghitungan yang efisien dengan array dan matriks dan menyediakan pustaka besar fungsi matematika tingkat tinggi yang beroperasi pada array dan matriks.

## Installing Numpy

In [ ]:
# pip install numpy

## How to import Numpy

In [ ]:
# import numpy as np

Why use Numpy?
Array Numpy lebih cepat dan lebih compact daripada list Python. Sebuah array mengonsumsi lebih sedikit memori untuk menyimpan data dan menyediakan mekanisme untuk menentukan tipe data, yang memungkinkan kode untuk dioptimalkan lebih jauh.

## Creating Array

In [2]:
import numpy as np
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

TypeError: array() missing required argument 'object' (pos 0)

Untuk membuat array Numpy, kalian dapat menggunakan fungsi np.array()

In [3]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
# you can easily create an array filled with 0s:

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
# or an array filled with 1s:

np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
# or an empty array
# the function empty creates an array whose initial content is random
# and depends on the state of the memory

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
# can create an array with a range of elements

print(np.arange(4))
print(np.arange(0, 10, 2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


## Add, Remove, and Sort

In [9]:
# np.append()
# np.delete()
# np.sort()

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

Menggunakan np.append() untuk menambahkan elemen ke array

In [14]:
np.append(arr, [1, 2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

Menghapus elemen menggunakan np.delete()

In [16]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

Mengurutkan elemen dapat menggunakan np.sort(). Kalian dapat menentukan axis, jenis, dan urutan saat memanggil fungsi.

In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [18]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [19]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

**array.ndim** akan memberi tahu kalian jumlah axes, atau dimensi, dari array.

**ndarray.size** akan memberi tahu kalian jumlah total elemen array. Ini adalah produk dari elemen shape array.

**ndarray.shape** akan menampilkan tuple integer yang menunjukkan jumlah elemen yang disimpan di sepanjang setiap dimensi array. Jika, misalnya, kalian memiliki larik 2D dengan 2 baris dan 3 kolom, maka bentuk larik Anda adalah (2,3).

In [25]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                           
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [26]:
array_example.ndim

3

In [27]:
array_example.size

24

In [28]:
array_example.shape

(3, 2, 4)

## Reshape

Menggunakan np.reshape() akan memberikan bentuk baru ke array tanpa mengubah datanya. Pastikan array yang ingin kalian hasilkan harus memiliki jumlah elemen yang sama dengan array asli.

In [29]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [30]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

Parameter opsional np.reshape():
numpy.reshape(a, newshape, order)

**a** adalah array yang akan di-reshaped
**newshape** adalah bentuk baru yang kalian inginkan.
**order** 'C' artinya membaca atau menulis element menggunkan C-like index order, 'F' artinya membaca/menulis menggunakan Fortran-like index order.

## Convert 1D to 2D

In [ ]:
# np.newaxis
# np.expand_dims

Menggunakan np.newaxis akan meningkatkan dimensi array kalian sebesar satu dimensi bila digunakan sekali. Artinya 1D menjadi array 2D, array 2D akan menjadi array 3D, dan seterusnya.

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [33]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [34]:
# you can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [35]:
# for a column vector, you can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Kalian juga dapat memperluas array dengan memasukkan axis baru pada posisi yang ditentukan dengan np.expand_dims.

In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
a

array([1, 2, 3, 4, 5, 6])

In [37]:
# you can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [41]:
# you can add an axis at index position 0 with:

c = np.expand_dims(a, axis = 0)
c.shape
c


array([[1, 2, 3, 4, 5, 6]])

## Index and Slicing

Mengindeks dan slice array Numpy dengan cara yang sama seperti slice lists Python.

In [42]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [45]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
# you can easily print all of the values in the array that are bigger than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [47]:
# you can also select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [48]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[ (a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [ ]:
# from copy import copy


# np.vstack()
# np.hstack()
# np.split()
# .view()
# .copy()

In [49]:
arr = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [50]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [51]:
a_1 = np.array([[1, 1],
                [2, 2]])

a_2 = np.array([[3, 3],
                [4, 4]]) 

np.vstack((a_1, a_2))               

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [52]:
np.hstack((a_1, a_2)) 

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [54]:
arrsplit = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [55]:
# if you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

Menggunakan metode view untuk membuat objek array baru yang terlihat sama dengan array asli (shallow copy)

In [56]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
# Create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
# using the copy method will make a complete of the array and its data (a deep copy)

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic Array Operations

In [59]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [60]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [61]:
# sum the rows

b.sum(axis=0)

array([3, 3])

In [62]:
# sum the columns
b.sum(axis=1)

array([2, 4])

In [63]:
data = np.array([1, 2])
data

array([1, 2])

In [64]:
ones = np.ones(2)
ones

array([1., 1.])

In [65]:
data + ones

array([2., 3.])

In [66]:
data * data

array([1, 4])

In [67]:
data / data

array([1., 1.])

## Broadcasting 

Ada kalanya ingin melakukan operasi antara array dan satu bilangan atau antara array dengan ukuran yang berbeda. Numpy memahami bahwa perkalian harus dilakukan dengan setiap sel. Konsep tersebut disebut broadcasting. Broadcasting adalah mekanisme yang memungkinkan Numpy melakukan operasi pada array dengan bentuk berbeda.

In [69]:
data * 3

array([3, 6])

## More Array Operations

Numpy juga melakukan agregasi. Selain **min, max, dan sum**, kalian bisa dengan mudah menjalankan **mean** untuk mendapatkan rata-rata, **prod** untuk mendapatkan hasil perkalian elemen, **std** untuk mendapatkan standar deviation, dan banyak lagi.

In [70]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [71]:
A.sum()

4.8595784

In [72]:
A.min()

0.05093587

In [74]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [75]:
A.max()

0.82485143

In [76]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [77]:
A.std()

0.21392120766089617

## Creating Matrices

In [78]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.17626522 0.26698235]
 [0.53052827 0.45849178]
 [0.02076871 0.28247335]]


## Matrix Arithmetic

Dapat menjumlahkan dan mengalikan matriks menggunakan operator aritmatika (+-*/) jika kedua matriks tersebut berukuran sama. Numpy menanganinya sebagai positon-wise operations.

In [79]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [80]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [81]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [82]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [85]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

Numpy memberi setiap matriks metode **dot()** yang dapat digunakan untuk menjalankan operasi dot product dengan matriks lain.

In [86]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [87]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

Operasi indexing dan slicing menjadi lebih berguna saat memanipulasi matriks.

In [88]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggragation

Menjumlahkan matriks dengan cara yang sama seperti kita menjumlahkan vektor.

In [89]:
print(data)
print(data.max())
print(data.min())
print(data.sum())

[[1 2]
 [3 4]
 [5 6]]
6
1
21


In [90]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

Kebutuhan umum saat menangani matriks adalah kebutuhan untuk rotate. Hal ini sering terjadi ketika kita perlu melakukan dot product dari dua matriks dan perlu menyelaraskan dimensi mereka. Array Numpy memiliki properti yang disebut T untuk mendapatkan transpos dari sebuah matriks.

In [91]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

Metode **reshape()** Numpy berguna dalam kasus ini.

In [93]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [94]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

Numpy dapat melakukan semua yang telah kita sebutkan dalam berbagai dimensi. Struktur data pusatnya disebut ndarray (N-Dimensional Array) karena suatu alasan.

In [96]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Dalam banyak hal, berurusan dengan dimensi baru hanyalah dengan menambahkan koma ke parameter fungsi NumPy

In [97]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [98]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [99]:
print(np.random.random((4,3,2)))

[[[0.29442451 0.62054517]
  [0.36404621 0.33485942]
  [0.90596454 0.15737182]]

 [[0.79417262 0.91511808]
  [0.91226156 0.81220677]
  [0.12130203 0.73620246]]

 [[0.24641087 0.21159461]
  [0.38447661 0.47282365]
  [0.44749254 0.72329278]]

 [[0.78703732 0.98823103]
  [0.4683142  0.79869612]
  [0.33207804 0.78986307]]]


## Flatten N-Dimensional Array

Ada dua cara populer untuk meratakan array: **.flatten()** dan **.ravel**. Perbedaan utama antara keduanya adalah bahwa array baru yang dibuat menggunakan .ravel() sebenarnya merupakan referensi ke array induk. Ini berarti bahwa setiap perubahan pada array baru akan memengaruhi array induk juga. Karena ravel tidak membuat salinan, ini menghemat memori.

In [100]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [101]:
# You can use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])